[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = -q
filterwarnings =
    ignore:The anyio\.abc\.BlockingPortal alias is deprecated.*:DeprecationWarning:starlette\.testclient
