"""add_gender_and_purchased_plans

Revision ID: 4de83f712c3e
Revises: 0d4fbe5a6196
Create Date: 2026-04-03 14:16:19.767858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de83f712c3e'
down_revision: Union[str, Sequence[str], None] = '0d4fbe5a6196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('purchased_plans', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'current_plan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_plan', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'purchased_plans')
    # ### end Alembic commands ###
