"""add generated_plans to user

Revision ID: f89678e8a00e
Revises: 4de83f712c3e
Create Date: 2026-04-17 11:50:26.558897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89678e8a00e'
down_revision: Union[str, Sequence[str], None] = '4de83f712c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('generated_plans', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'generated_plans')
    # ### end Alembic commands ###
